[phases.setup]
nixPkgs = ["python3", "gcc", "python3-pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "source /opt/venv/bin/activate && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
